spring:
  application:
    name: forum-service
  datasource:
    url: jdbc:postgresql://cohort5860-cohort5860fs.c.aivencloud.com:12564/defaultdb
    username: avnadmin
    password: ${AIVEN_PASS}
  jpa:
    hibernate:
#      auto ставим внмзу чтоб гибернет сам создавал струтуру бд , а если создаем сами в ликвидбейс то ставим нон
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml