#Forum

@host = http://localhost:8080/forum/post
@user = JavaSCFan
@postId = 11
@commenter = Stranger




###
# Add Post
POST {{host}}/{{user}}
Content-Type: application/json

{
  "title": "JavaEE",
  "content": "Java is the best for backend",
  "tags": ["Java", "Spring", "backend", "JEE"]
}

###
# Find post by ID
GET {{host}}/{{postId}}

###

# Add like
PATCH {{host}}/{{postId}}/like

###

# Find posts by author
GET {{host}}/author/{{user}}

###

# Add comment
PATCH {{host}}/{{postId}}/comment/{{commenter}}
Content-Type: application/json

{
  "message": "Awesome!!!"
}

###

# Delete post
DELETE {{host}}/{{postId}}

###

# Find posts by tags
GET {{host}}/tags?values=python,java,j2ee

###

# Find posts by period
GET {{host}}/period?dateFrom=2020-08-25&dateTo=2026-08-21

###

# Update post
PATCH {{host}}/{{postId}}
Content-Type: application/json

{
  "title": "Jakarta EE",
  "tags": ["Jakarta EE", "J2EE"]
}